### ISSUE TITLE
Enhance Friendify Addon with Custom Voicelines

### ISSUE THREAD

**Issue by StrappingProgrammerLad** [cd21/Mariofy#3]
# Task: Enhance Friendify Addon with Custom Voicelines

## Description
Upgrade the existing Mariofy addon to "Friendify" by integrating custom voicelines that trigger in response to specific in-game events. This feature aims to provide audio feedback for various actions and situations in the game. The addon will play custom sound files for the voicelines written in Lua.

## Features to Implement

1. **Healing and Potions**
   - Play a voiceline when the player receives a heal.
   - Play a voiceline when the player uses a potion.

2. **Engagement Scenarios**
   - Play distinct voicelines for:
     - Normal mob engagement.
     - Boss engagement.
     - Elite mob engagement.

3. **Critical Hits**
   - Play a voiceline when the player receives a critical hit.
   - Play a voiceline when the player deals a critical hit.

4. **Low Resource Warnings**
   - Play a voiceline when the player has low health.
   - Play a voiceline when the player has low mana.

5. **Buff Interactions**
   - Play a voiceline when the player receives a buff.
   - Play a voiceline when the player applies a buff to someone else.

6. **Mob Types**
   - Play a voiceline when targeting a red (aggressive) mob.
   - Play a voiceline when targeting a skull (high-level/dangerous) mob.

7. **Miscellaneous Actions**
   - Play a voiceline when taking a flight path.
   - Play a voiceline when returning from AFK status.
   - Play a voiceline when eating or drinking.

## Development Steps

1. **Add Sound Files**
   - Store all voiceline sound files in a dedicated folder (`sounds/`) within the addon directory.
   - Ensure all sound file names match the event triggers (e.g., `heal.wav`, `potion.wav`).

2. **Event Handlers**
   - Write event handlers in Lua for all specified game events.
   - Use `COMBAT_LOG_EVENT_UNFILTERED` for combat-related triggers (e.g., critical hits, engagements).
   - Use appropriate WoW API functions (e.g., `PLAYER_REGEN_DISABLED`, `UNIT_HEALTH`) for resource-related and other triggers.

3. **Sound Playback**
   - Create a reusable `playSound` function to play voicelines for each trigger. Example:
     ```lua
     local function playSound(name)
         PlaySoundFile("Interface\\AddOns\\Friendify\\sounds\\" .. name .. ".wav", "Master")
     end
     ```

4. **Event Registration**
   - Register events like `UNIT_SPELLCAST_SUCCEEDED`, `CHAT_MSG_SYSTEM`, `COMBAT_LOG_EVENT_UNFILTERED`, and more as needed.

5. **Testing**
   - Test each trigger to ensure the correct voiceline plays for each event.

## Acceptance Criteria
- [ ] Each event reliably triggers the correct voiceline.
- [ ] Sound files are properly loaded from the addon directory.
- [ ] No errors or performance issues occur during gameplay.
- [ ] Events are appropriately throttled to avoid sound spam (e.g., cooldowns on low health or mana triggers).
